version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
linters:
  default: none
  exclusions:
    rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
formatters:
  enable:
  - gofmt
  - goimports
