# permissions for end users to edit repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: output-dir
    app.kubernetes.io/managed-by: kustomize
  name: repository-editor-role
rules:
- apiGroups:
  - github.github-operator.eczy.io
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.github-operator.eczy.io
  resources:
  - repositories/status
  verbs:
  - get
