---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github-operator.eczy.io
  resources:
  - branchprotectionrules
  - organizations
  - repositories
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github-operator.eczy.io
  resources:
  - branchprotectionrules/finalizers
  - organizations/finalizers
  - repositories/finalizers
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - github-operator.eczy.io
  resources:
  - branchprotectionrules/status
  - organizations/status
  - repositories/status
  - teams/status
  verbs:
  - get
  - patch
  - update
