---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - github.github-operator.eczy.io
  resources:
  - branchprotections
  - organizations
  - repositories
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.github-operator.eczy.io
  resources:
  - branchprotections/finalizers
  - organizations/finalizers
  - repositories/finalizers
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - github.github-operator.eczy.io
  resources:
  - branchprotections/status
  - organizations/status
  - repositories/status
  - teams/status
  verbs:
  - get
  - patch
  - update
