apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - branchprotections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - branchprotections/finalizers
    verbs:
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - branchprotections/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - organizations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - organizations/finalizers
    verbs:
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - organizations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - repositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - repositories/finalizers
    verbs:
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - repositories/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - teams
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - teams/finalizers
    verbs:
      - update
  - apiGroups:
      - github.github-operator.eczy.io
    resources:
      - teams/status
    verbs:
      - get
      - patch
      - update
