# This rule is not used by the project github-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to github-operator.eczy.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: team-viewer-role
rules:
- apiGroups:
  - github-operator.eczy.io
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github-operator.eczy.io
  resources:
  - teams/status
  verbs:
  - get
