apiVersion: github.github-operator.eczy.io/v1alpha1
kind: Team
metadata:
  labels:
    app.kubernetes.io/name: team
    app.kubernetes.io/instance: team-sample
    app.kubernetes.io/part-of: github-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: github-operator
  name: team-sample
spec:
  name: test-team
  organization: test-organization
