name: PR checks
on:
  pull_request:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: make test
        env:
          GITHUB_OPERATOR_TEST_ORG: ${{ vars.OPERATOR_TEST_ORGANIZATION }}
          GITHUB_OPERATOR_RECORDER_MODE: replay-only
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.0.2
      - name: Install yamlfmt
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Run yamlfmt
        run: yamlfmt -lint -quiet .
